site_name: Open Stage Control
repo_name: open-stage-control
repo_url: https://github.com/jean-emmanuel/open-stage-control
edit_uri: tree/master/resources/docs/
copyright: "Open Stage Control is an <a href='http://ammd.net'>AMMD</a> software licensed under the <a href='https://github.com/jean-emmanuel/open-stage-control/blob/master/LICENSE'>GNU/GPLv3</a> License"
site_description: "Libre and modular OSC / MIDI controller"

theme:
    name: 'material'
    custom_dir: 'theme'
    # font: false
    features:
        - tabs
        - instant
    palette:
        primary: 'Black'
        accent: 'Indigo'
    logo: 'img/logo.png'
    favicon: 'img/logo_nobadge.png?6'
    # static_templates:
    #   - 404.html

extra_css:
  - 'extra/styles.css'

extra:
    screenshot: img/ardour-osc.png
    links:
        -
            title: Download
            url: https://github.com/jean-emmanuel/open-stage-control/releases
            primary: true
        -
            title: Try online (requires chromium 50+)
            url : http://openstagecontrol.herokuapp.com

nav:
    - Home: index.md
    - Download:
        - download.md
    - Documentation:
        - Getting started:
            - docs/getting-started/server-setup.md
            - docs/getting-started/supported-platforms.md
            - docs/getting-started/running-from-sources.md
            - docs/getting-started/running-with-node.md
        - User interface:
            - docs/user-interface/user-interface.md
            - docs/user-interface/editor.md
            - docs/user-interface/keyboard-shortcuts.md
        - Widgets:
            - docs/widgets/general-mechanics.md
            - docs/widgets/properties-reference.md
            - docs/widgets/advanced-syntaxes.md
            - docs/widgets/scripting.md
        - MIDI:
            - MIDI setup: docs/midi/midi-setup.md
            - MIDI messages: docs/midi/midi-messages.md
        - Custom module:
            - docs/custom-module/custom-module.md
            - docs/custom-module/examples.md
            - docs/custom-module/managing-big-modules.md
        - Customization:
            - docs/customization/themes.md
            - docs/customization/css-tips.md
        - Client options: docs/client-options.md
        - Remote control: docs/remote-control.md
        - Credits: docs/credits.md

    - Bug Tracker:
        - 'Bug Tracker': 'https://github.com/jean-emmanuel/open-stage-control/issues'
    - Community:
        - 'Community forums': 'https://openstagecontrol.discourse.group'

markdown_extensions:
    - markdown.extensions.extra
    - markdown.extensions.admonition
    - codehilite:
        guess_lang: False
    - markdown.extensions.def_list
    - markdown.extensions.footnotes
    - markdown.extensions.meta
    - markdown.extensions.toc:
        permalink: "#"
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
#
# plugins:
#     - search
